apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  selector:
    matchLabels:
      name: app2
  replicas: 1
  template:
    metadata:
      labels:
        name: app2
    spec:
      containers:
        - name: app2
          image: localhost:5555/nodejs1
          command:
            - /bin/sh
            - -c
            - '/appd-start.sh'
          envFrom:
            - configMapRef:
                name: appdynamics-common
            - secretRef:
                name: appdynamics-secrets
          imagePullPolicy: Always
          volumeMounts:
          - name: appd-start-js
            mountPath: /appd-start.js
            subPath: appd-start.js
          - name: appd-start-sh
            mountPath: /appd-start.sh
            subPath: appd-start.sh
          ports:
          - containerPort: 8081
      restartPolicy: Always
      volumes:
      - configMap:
          name: appd-start-js
          defaultMode: 511
        name: appd-start-js
      - configMap:
          name: appd-start-sh
          defaultMode: 511
        name: appd-start-sh
---
apiVersion: v1
kind: Service
metadata:
  name: app2
spec:
  selector:
    name: app2
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  clusterIP: None
