#!/bin/bash
#
#

DOCKER_TAG_NAME="nodejs1"
DOCKER_REPOSITORY_ACCOUNT="localhost:5555"
DOCKER_REPOSITORY_TAG_NAME=$DOCKER_REPOSITORY_ACCOUNT/$DOCKER_TAG_NAME

docker build -t $DOCKER_TAG_NAME .


docker tag  $DOCKER_TAG_NAME  $DOCKER_REPOSITORY_TAG_NAME
docker push $DOCKER_REPOSITORY_TAG_NAME
